version: '3.6'

services:
  spacegraph:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: johncapobianco/spacegraph:latest
    container_name: spacegraph
    restart: always
    ports:
      - "2024:2024"
    env_file:
      - .env